In [1]:
import numpy as np
import pandas as pd
import viz
np.random.seed(29)

In [2]:
#How likely is it that you roll doubles when rolling two dice?

n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[6, 4],
       [5, 6],
       [3, 1],
       ...,
       [2, 5],
       [1, 4],
       [4, 6]])

In [3]:
isdoubles = pd.DataFrame(rolls)
isdoubles[isdoubles.duplicated()]

0  1
5     6  4
6     2  1
15    5  3
18    1  3
19    1  3
...  .. ..
9995  5  2
9996  3  6
9997  2  5
9998  1  4
9999  4  6

[9964 rows x 2 columns]

In [4]:
#take dataframe setup boolean, see if col one equals col 2
#number of true divided by total rows
(isdoubles[1] == isdoubles[0]).mean()


0.1709

In [5]:
# If you flip 8 coins, what is the probability of getting exactly 3 heads? 
# What is the probability of getting more than 3 heads?



In [6]:
n_trials = nrows = 10_000
n_dice = ncols = 8

flips = np.random.choice(['heads','tails'], n_trials * n_dice).reshape(nrows, ncols)
flips

array([['heads', 'heads', 'heads', ..., 'heads', 'tails', 'tails'],
       ['heads', 'heads', 'tails', ..., 'tails', 'tails', 'heads'],
       ['tails', 'heads', 'tails', ..., 'tails', 'tails', 'tails'],
       ...,
       ['heads', 'tails', 'heads', ..., 'tails', 'tails', 'heads'],
       ['tails', 'heads', 'heads', ..., 'tails', 'tails', 'tails'],
       ['tails', 'heads', 'heads', ..., 'heads', 'tails', 'heads']],
      dtype='<U5')

In [10]:
#moved to a different setup bc I couldnt get the 'heads' and 'tails' version to work,
coins = pd.DataFrame(np.random.randint(0,2,(1000000,8)))

In [12]:
#probability of three heads
p_three_heads = (coins.sum(axis=1) == 3).mean()

p_three_heads


0.218598

In [13]:
#probability of over three
p_over_three = (coins.sum(axis=1) > 3).mean()

p_over_three

0.63616

In [ ]:
# There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
# Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that 
# the two billboards I drive past both have data science students on them?

In [30]:
billboards = np.random.random((1000000,2))
#1 ds 3 web dev, .25
dsstudents = (billboards <= .25).prod(axis=1).mean()
dsstudents

0.062011

In [ ]:
# Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the 
# snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is 
# it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard 
# deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [17]:
#3 poptarts a day with 1.5 std, 5 days a week
poptarts = np.random.normal(3, 1.5, (1000000,5))
poptarts = poptarts.round()
#probability of poptarts with 17 available...on friday
_friday = (poptarts.sum(axis = 1)<= 16).mean()
_friday

0.66997

In [ ]:
# Compare Heights

# Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.
# Since you have means and standard deviations, you can use np.random.normal to generate observations.
# If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [18]:
#np.random.normal(mean,std, trials)
men = np.random.normal(178, 8, 1000000)
men

array([171.48760266, 180.89658916, 173.12083277, ..., 169.25570989,
       171.73276698, 167.84786464])

In [19]:
women = np.random.normal(170, 6, 1000000)
women

array([171.14667632, 184.5996602 , 164.1748521 , ..., 174.81674828,
       171.25980244, 175.11495184])

In [20]:
#probability of variables as setup previously where women > men
ptallerwoman = (women > men).mean()
ptallerwoman

0.211684

In [ ]:
# When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted 
# and the installation fails. What are the odds that after having 50 students download anaconda, no one has an 
# installation issue? 100 students?

# What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [23]:
failrate = 1/250
nofail_fifty = (np.random.random((10000,50))> failrate).prod(axis=1).mean()
nofail_fifty

0.816

In [25]:
nofail_hundred = (np.random.random((10000,100)) > failrate).prod(axis=1).mean()
nofail_hundred

0.6714

In [27]:
nofail_hunredfifty = (np.random.random((10000,150)) > failrate).prod(axis=1).mean()
nofail_hunredfifty

0.5499

In [29]:
nofail_fourfifty = (np.random.random((10000,450))> failrate).prod(axis = 1).mean()
nofail_fourfifty

0.1689

In [ ]:
# There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 
# However, you haven't seen a food truck there in 3 days. How unlikely is this?

# How likely is it that a food truck will show up sometime this week?

In [31]:
threedays = (np.random.random((10000,3))> .7).prod(axis=1).mean()
threedays

0.0272

In [50]:
#need to revisit this part

restofweek = np.random.choice([0,1], size = (10000,4), p=[.3,.7]).mean()

restofweek

0.698075

In [ ]:
# If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [34]:
bday_twentythree = pd.DataFrame(np.random.randint(0,365,(10000,23)))
same_bdaytwentythree = bday_twentythree.apply(lambda x: len(set(x)) != len(x), axis=1).mean()
same_bdaytwentythree

0.5015

In [35]:
bday_twenty = pd.DataFrame(np.random.randint(0,365, (10000, 20)))
same_bdaytwenty = bday_twenty.apply(lambda x: len(set(x))!= len(x),axis=1).mean()
same_bdaytwenty

0.408

In [36]:
bday_forty =  pd.DataFrame(np.random.randint(0,365,(10000,40)))
same_bdayforty = bday_forty.apply(lambda x: len(set(x)) != len(x), axis=1).mean()
same_bdayforty

0.8913